server:
  port: 8086
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/resource_mgmt
    username: root
    password: password
  jpa:
    generate-ddl: true
    show-sql: true

logging:
  level:
    org:
      springframework: ERROR

